"""implement relationships

Revision ID: d625a72b28f2
Revises: b3b743c70add
Create Date: 2024-04-24 23:04:24.657382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd625a72b28f2'
down_revision = 'b3b743c70add'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('missions', sa.Column('planet_id', sa.Integer(), nullable=True))
    op.add_column('missions', sa.Column('scientist_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_missions_scientist_id_scientists'), 'missions', 'scientists', ['scientist_id'], ['id'])
    op.create_foreign_key(op.f('fk_missions_planet_id_planets'), 'missions', 'planets', ['planet_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_missions_planet_id_planets'), 'missions', type_='foreignkey')
    op.drop_constraint(op.f('fk_missions_scientist_id_scientists'), 'missions', type_='foreignkey')
    op.drop_column('missions', 'scientist_id')
    op.drop_column('missions', 'planet_id')
    # ### end Alembic commands ###
